---
output:
  word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




Dear Editor,

Please find attached our manuscript entitled “Drivers and vulnerability of global coral reef fish functions” for consideration as a research article in Nature. 
     
Focusing on coral reefs, we have performed the largest collection of reef fish physiological traits to date and used novel bioenergetic models to quantify five key ecosystem functions at a global scale for the first time; biomass production, nitrogen and phosphorous cycling, herbivory and predation. Our global analysis reveals a trade-off between different functions, challenging the classical view of ‘healthy’ reefs maximizing across multiple functions. Indeed, we show that at a given biomass, coral reefs display a large array of functional configurations. We demonstrate that this variability within and among functions is driven by community structure and species dominance. However, while local species dominance is a major driver of ecosystem functioning, the identity of dominant species varies among reefs, thus challenging the applicability of conservation practices related to the concept of keystone species. Finally, we illustrate the variable vulnerability of functions to two major stressors: overfishing and coral loss.
             
We believe our manuscript is ideally suited for the broad readership of Nature because, 1) it provides the first global maps of ecosystem functioning for coral reefs; 2) it challenges the mainstream view of maximizing multiple functions concurrently; and 3) it identifies the key drivers of coral reef functioning at a global scale, which is crucial for the conservation of this vulnerable ecosystem. In light of the fundamental importance of coral reefs for humanity, the ecological complexity of this hyperdiverse ecosystem, and the intensifying anthropogenic threats to coral reefs, we believe the study will be of great interest to a wide array of scientists, policy makers, conservation practitioners, and the general public.  
               
Thank you for your consideration. We look forward to working with you during the editorial process.  


Kind regards,


Nina M. D. Schiettekatte, on behalf of all co-authors