---
output:
  word_document:
    fig_caption: yes
    reference_docx: ../text/word_template.docx
bibliography: ../text/global_proc.bib
csl: nature.csl
---



# **Title:** Biological trade-offs underlie coral reef ecosystem functioning

**Authors:** Nina M. D. Schiettekatte^1,2,\*^, Simon J. Brandl^3^, Jordan M. Casey^3^, Nicholas A. J. Graham^4^, Diego R. Barneche^5,6^, Deron E. Burkepile^7,8^, Jacob E. Allgeier^9^, Jesús E. Arias-Gonzaléz^10^, Graham J. Edgar^11^, Carlos E. L. Ferreira^12^, Sergio R. Floeter^13^, Alan M. Friedlander^14^, Alison L. Green^15^, Michel Kulbicki^2,16^, Yves Letourneur^2,17^, Osmar J. Luiz^18^, Alexandre Mercière^1,2^, Fabien Morat^1,2^, Katrina S. Munsterman^9^, Enrico L. Rezende^19^, Fabian A. Rodríguez‐Zaragoza^20^, Rick D. Stuart-Smith^11^, Laurent Vigliola^2,16^, Sébastien Villéger^21^, Valeriano Parravicini^1,2^


**Affiliations:**
^1^PSL Université Paris: EPHE-UPVD-CNRS, USR 3278 CRIOBE, Université de Perpignan, Perpignan, France;
^2^Laboratoire d'Excellence “CORAIL”, Perpignan, France;
^3^Department of Marine Science, The University of Texas at Austin, Marine Science Institute, Port Aransas, TX 78373, USA;
^4^Lancaster Environment Centre, Lancaster University, Lancaster, LA1 4YQ, UK;
^5^Australian Institute of Marine Science, Crawley, WA, Australia;
^6^Oceans Institute, The University of Western Australia, Crawley, WA, Australia;
^7^Department of Ecology, Evolution, and Marine Biology, University of California, Santa Barbara, CA, USA;
^8^Marine Science Institute, University of California, Santa Barbara, CA, USA;
^9^Department of Ecology and Evolutionary Biology, University of Michigan, Ann Arbor, MI, USA;
^10^Laboratorio Ecología de Ecosistemas de Arrecifes Coralinos, Departamento Recursos del Mar, CINVESTAV Unidad Mérida, AP73 Cordemex, CP97310, Mérida, Yucatán, Mexico;
^11^Institute for Marine and Antarctic Studies, University of Tasmania, Hobart, TAS, Australia;
^12^Departamento de Biologia Marinha, Universidade Federal Fluminense (UFF), Niterói,  the state of Rio de Janeiro (RJ), Brazil;
^13^Marine Macroecology and Biogeography Lab, Depto. de Ecologia e Zoologia, CCB, Universidade Federal de Santa Catarina, Florianopolis, Santa Catarina, Brazil;
^14^Department of Biology, University of Hawaii, Honolulu, HI, USA;
^15^Red Sea Research Center, King Abdullah University of Science and Technology, Thuwal 23955-6900, Saudi Arabia;
^16^Institut de Recherche pour le Développement, UMR UR-IRD-CNRS-IFREMER-UNC ENTROPIE, Nouméa, New Caledonia, France;
^17^Université de la Nouvelle-Calédonie, UMR UR-IRD-CNRS-IFREMER-UNC ENTROPIE, Nouméa, New Caledonia, France;
^18^Research Institute for the Environment and Livelihoods, Charles Darwin University, Darwin, Australia;
^19^Departamento de Ecología, Center of Applied Ecology and Sustainability (CAPES), Facultad de Ciencias Biológicas, Pontificia Universidad Católica de Chile, Santiago 6513677, Chile;
^20^Laboratorio de Ecosistemas Marinos y Acuicultura (LEMA), Departamento de 12 Ecología, CUCBA, Universidad de Guadalajara. México. Carr. Guadalajara-Nogales 13 km. 15.5, Las Agujas Nextipac, Zapopan, C.P. 45110, Jalisco, 14, Mexico;
^21^MARBEC, Université de Montpellier, CNRS, IFREMER, IRD, Montpellier, France
^\*^Correspondance to NMDS (nina.schiettekatte@gmail.com).

**One Sentence Summary:** A global assessment reveals critical trade-offs among multiple ecosystem functions performed by coral reef fishes.

\newpage

**Abstract:**
Preserving coral reef functioning is a critical challenge of the 21st century. However, a lack of quantitative assessments of multiple functions across large spatial scales has hindered local and regional conservation efforts. We integrate empirically-parametrized bioenergetic models and global community surveys to quantify five key functions mediated by coral reef fishes. We show that functions exhibit critical trade-offs driven by varying community structures such that no community can maximize all functions. Further, functions are locally dominated by few species, but the identity of dominant species substantially varies at the global scale. In fact, roughly half of the 1,110 species in our dataset are functionally dominant on a local scale. Our results reinforce the need for a nuanced, locally tailored approach to coral reef conservation that considers multiple ecological functions beyond the effect of standing stock biomass.

**Main Text:**
The flow of elements through biological communities fuels all ecosystems on earth [@Welti2017]. Humans increasingly threaten biodiversity and ecosystem functioning [@Ceballos2015].
Coral reefs are a prime example of an ecosystem severely impacted by anthropogenic activities.
Drastic declines in habitat quality and fish biomass have evoked serious concerns about the persistence of coral reefs [@Hughes2017; @Pauly2002].
Maintaining ecosystem functions, defined as fluxes of elements, is a major goal for conservation of coral reefs [@Bellwood2019; @Williams2019; @Brandl2019front].
However, past evaluations of functions on coral reefs have mostly relied on static proxies such as live coral cover, standing stock biomass of reef fishes, or measures of diversity [@Cinner2020; @Mouillot2014; @Mora2011].
These simplified proxies, although useful, may not properly represent ecological functions because the fluxes of elements can scale non-linearly with variables such as biomass [@Barneche2014].
Therefore, improving the quantification of ecological functions constitutes an important step towards the efficient management of coral reef ecosystem functioning [@Brandl2019front].

As a dominant group of consumers, coral reef fishes are essential vectors of carbon (C), nitrogen (N) and phosphorus (P) [@McIntyre2008; @Allgeier2014; @Barneche2014].
Ecosystem functions mediated by coral reef fishes include nutrient cycling, biomass production, herbivory, and piscivory (secondary consumption) (@Brandl2019front).
While the high diversity of coral reef fishes has inspired many studies that focus on ecosystem functioning, only a handful of studies have attempted to actually quantify functions as continuous fluxes [@Brandl2019front]. Further, studies that quantify functions as a flow of matter mostly focus on single functions (e.g. biomass production [@Morais2019; @Morais2020glob] or fish excretion [ @Allgeier2014]) and are restricted to a small number of species and local scales.
Consequently, trade-offs amongs multiple functions, their drivers, and their vulnerability to anthropogenic stressors remain poorly understood in coral reef ecosystems across large spatial scales [@Brandl2019front].

Here, we integrate biogeochemistry and community ecology to advance our understanding of the elemental fluxes that underpin reef fish functioning.
Using empirical species-specific data on basic organismal processes and Bayesian phylogenetic models, we parameterize individual-level bioenergetic models to estimate five key ecosystem functions: N excretion, P excretion, biomass production, herbivory, and piscivory for 1,100 species.
We apply these bioenergetic models to 9,118 reef fish transects across 585 sites worldwide (Table S1) to:
(1) quantify community-level reef fish functions and their trade-offs,
(2) extract the community- and species-level effects on these functions, and
(3) gauge the vulnerability of reef fish functioning in the Anthropocene.

## Results
We quantified five key ecosystem functions mediated by coral reef fishes across the globe (Fig. 1). Functions across localities show a similar geographocal pattern. However, at the global scale we could not find a single location with high levels of functioning across all functions. A measure of multifunctionality thus does not appropriately represent the state of all functions.

Biomass is the most commonly employed indicator of coral reef functioning [@Cinner2020; @Brandl2019front], and we demonstrate a predictably strong relationship between fish biomass and all five functions (Fig. 1). Specifically, in a multivariate mixed effects Bayesian model, the slopes of the log-transformed biomass were 0.932 (95\%CI: 0.929, 0.934) for N excretion, 1.051 (1.047, 1.056) for P excretion, 0.771 (0.764, 0.780) for production, 0.940 (0.923, 0.957) for herbivory, and 0.668 (0.635, 0.702) for piscivory. These slopes indicate that the relationships between biomass and functions are all non-linear, which demonstrates that biomass is not an appropriate proxy for function. We also incorporated sea surface temperature (SST) because it affects the metabolic and growth rates of fishes, which scales up to the community [@Barneche2019]. We found positive effects of SST on N excretion, production, and herbivory, and no effects of SST on P excretion and piscivory (table S3).


The forementioned multivariate model also allowed us to estimate the correlations between functions, independent of the effects of biomass and SST.
In particular, we estimated correlations between functions on three levels: the locality effects, site effects, and residual variations (Fig. 2, Fig. S1).
The correlations displayed comparable patterns on each level.
We found strong negative trade-offs between P excretion and N excretion as well as P excretion and biomass production. Further, we found slightly weaker negative correlations between piscivory and N excretion as well as piscivory and herbivory. Thus, a reef fish community does not simultaneously display high values of functioning across all investigated functions.

To explore what drives the variation and trade-offs of functions beyond the effects of biomass and SST, we ran a multivariate Bayesian mixed effects model by adding ten variables that describe the structure of each fish assemblage: species richness and the median, lower, and upper 95% quantiles of size, immaturity, and trophic level of individuals inside a community.
Each of these components have non-zero effects on at least one of the five functions, suggesting that the observed trade-offs may be, at least in part, rooted in the structure of the focal community (Fig. 3; Table S4).

Beyond community structure, we examined whether functions are driven by specific species across sites. We quantified the degree of dominance inside each community at the site-level and found that, on average, functions are dominated by a small fraction of the species in each community (Fig. 4a).
We also calculated the proportion of species that is dominant in at least one transect (i.e. species with a disproportionally high contribution as compared to a community in which all species contribute equally). However, we also found that at a global scale many species play a dominant role. In particular, 49\% of all species contributed disproportionally to a function in at least one community (Fig. 4b).
Yet, very few species are dominant throughout their range (Fig. 4c). Thus, functions within communities tend to be driven by few dominant species, but the identity of those dominant species varies across sites.


## Discussion

By quantifying five key processes mediated by coral reef fishes, we demonstrate that coral reef ecosystem functioning is shaped by biological trade-offs, local community structure, and species identity. Standing biomass is one of the most commonly employed indicators of coral reef functioning [@Cinner2020; @Brandl2019front], and our analyses confirm the pervasive influence of biomass on all other processes. Yet, our results also show non-linear relationships between functions and biomass and suggest that biomass alone does not sufficiently characterize functioning, as we found strong trade-offs among the five functions independent of biomass. Using biomass as a proxy might, therefore, mask fundamental differences in community-level functioning. Furthermore, for a given value of biomass, no reef can yield above average values across all five functions. While a reef may stand out as a hotspot for one function, no reef can maximize all functions simultaneously.


The observed trade-offs among functions are driven by fish community structure and the organismal physiology and life-history traits of its consituents [@Schiettekatte2020; @Schramski2015].
For example, we observed a clear trade-off between P excretion and biomass production which is mostly driven by the age and trophic structure.
Communities dominated by fishes with high trophic levels are charachterized high P excretion rates because predatory fishes have a P-rich diet [@Allgeier2014].
In contrast, biomass production is high in communities dominated by fishes that occupy low trophic levels because herbivores tend to exhibit higher growth rates [@Morais2018].
Moreover, P is retained for skeletal growth in young fishes, thus limiting P excretion rates [@Schiettekatte2020; @Hood2005].
Furthermore, metabolic theory predicts that small-bodied individuals have higher mass-specific metabolic rates, leading to elevated consumption rates and disproportionate contributions to functions that rely on rapid energetic turnover such as herbivory, piscivory, production, and N excretion [@Barneche2018; @Morais2020glob; @Brandl2019science].


Our results also reveal that functions consistently rely on a few dominant species, but the identities of local, dominant species strongly vary across sites [@Lefcheck2019].
Locally, a small number of high-performing taxa may disproportionately impact rates of functioning at the community level due to high biomass or abundance [@Topor2019], which may have led to their designation as functionally-dominant “key species” in various locations [@Bellwood2006].
However, our results revealed that no species dominated throughout their geographical range, and more than half of all species contributed disproportionally to a specific function at a at least one site.
Thus, there are no widespread key species to target for coral reef conservation; rather, local species dominance across functions can guide local conservation efforts, and the preservation of regional reef fish biodiversity should be prioritized in broad-scale policy.

Our global analysis of multiple functions suggests pathways in which human-induced shifts in reef fish community structure may impact coral reef ecosystems (Fig. 5).
Fishing and climate-induced coral loss have caused declines in reef fish biomass and shifts in community structure [@Darling2017; @Graham2017], and we suggest that these changes will differentially affect ecosystem functioning.
Intensive fishing and associated reductions in the biomass of large fishes, for example, alters the size, age, and trophic structure of fish communities [@Graham2017].
When accounting for the effect of biomass, these community shifts can enhance N excretion and production [e.g. @Morais2020glob], but they will negatively impact P excretion, herbivory, and piscivory.
Further, declines in coral cover related to climate change are often associated with shifts toward herbivores [@Graham2006].
Herbivores generally contribute little to P excretion [@Allgeier2014; @Schiettekatte2020], so a shift to herbivore dominance and the subsequent decline of community-level P excretion may change the balance of nutrient cycling on coral reefs, potentially favoring algal growth over corals [@Burkepile2013].


Sustaining biomass, diversity, and ecosystem functioning are important objectives of most conservation initiatives [@Cinner2020].
While safeguarding fish biomass enhances functioning, the trade-offs between key functions reveal a critical challenge for coral reef conservation, where actions to enhance one function may negatively impact another.
For example, the establishment of marine protected areas, which are one of the primary conservation stratigies for coral reefs [@Graham2020], may protect herbivorous species.
However, marine protected areas do not protect reefs from the pervasive effects of climate change [@Graham2020], and community shifts towards herbivore domination may result in the decline of P excretion.
Thus, measuring conservation success with biomass or solely one function (e.g. herbivory) can mask the collapse of other essential functions.
It is necessary to gauge the state of reef ecosystems based on multiple, complementary, process-based functions.
Yet, our comprehension of process-based functioning or the definition a “functional” coral reef is still poorly understood [@Brandl2019front].
Establishing functional baselines for global coral reefs is a critical challenge for future studies.
Until then, our results suggest that coral reef fish functions can be managed by enhancing standing stock biomass, protecting local key species and vulnerable consituents of the community (e.g. large carnivores), and promoting regional biodiversity.


We demonstrate that the variability in processes that govern the elemental cycling in complex ecosystems such as tropical coral reefs represents an unrecognized challenge for protecting ecosystem functioning. Management strategies that call for the enhancement of ecosystem functioning via an economic mindset (i.e. where higher functioning is better) are not feasible. Instead, conserving coral reef ecosystem functioning will require a more nuanced approach that considers processes that vary beyond the effect of standing stock biomass and are subject to local trade-offs, drivers, and anthropogenic threats.

## Methods

### 1. Underwater visual census database
\noindent We used a published global database of reef fish abundances and sizes collected along belt transects [@Barneche2019]. This database encompasses 9,118 transects across 585 sites (within 98 localities) in the Central Indo-Pacific, Central Pacific, Eastern Pacific, Western Indian, Eastern Atlantic, and Western Atlantic Oceans. Sites are defined as small islands or stretches of continuous reefs in larger coastlines and localities encompass sites that belong to the same biogeographic sub-provinces [see @Barneche2019]. The database only includes transects on the outer reef slope and with a hard reef bottom. Transects were carried out at a constant depth, parallel to the reef crest. We discarded the species inside families for which we did not have body stoichiometry data, individuals that were smaller than 7cm (to minimize the bias related to the identification of small individuals), and rare species for which less than 20 individuals were recorded across all transects. The dataset then included 1,110 species belonging to 25 families (Acanthuridae, Balistidae, Bothidae, Chaetodontidae, Cirrhitidae, Fistulariidae, Haemulidae, Holocentridae, Kyphosidae, Labridae, Lethrinidae, Lutjanidae, Monacanthidae, Mugilidae, Mullidae, Ostraciidae, Pempheridae, Pomacanthidae, Pomacentridae, Sciaenidae, Scorpaenidae, Serranidae, Siganidae, Tetraodontidae, Zanclidae).
Sea surface temperature (SST) for each site was obtained from daily time‐series data from the National Oceanicand Atmospheric Administration (NOAA) covering a 5‐year period (°C; 0.25° resolution) (@Reynolds2007; available from https://www.esrl.noaa.gov/psd/data/gridded/data.noaa.oiSST.v2.highres.html). Further, for each transect, we calculated species richness and estimated total standing stock biomass of fishes by using Bayesian length-weight relationships available from Fishbase [@Froese2014]. All data processing and analyses were performed in the software program R (version 4.0.2; R core team 2020).

### 2. Quantification of functions
\noindent For each transect, we estimated five key process-based functions mediated by fishes: nitrogen excretion rate (gN m^-2^ day^-1^), phosphorus excretion rate (gP m^-2^ day^-1^), production of biomass through growth (gC m^-2^ day^-1^), herbivory, (i.e. ingestion rate of macrophytes (gC m^-2^ day^-1^)), and piscivory (i.e. ingestion rate of fishes ( m^-2^ day^-1^)) [@Brandl2019front]. These five functions were estimated for each transect using individual-based bioenergetic models predicting fluxes of carbon (C), nitrogen (N), and phosphorus (P) (e.g. daily C intake rates, N and P excretion rates, and growth rates) [@Schiettekatte2020].
This bioenergetic model framework integrates elements of metabolic theory, stoichiometry, and flexible elemental limitation [@Schiettekatte2020]. We quantified the input parameters, including elements of metabolism, growth, and diet and body stoichiometry, for all 1110 species through the integration of empirical data, data synthesis, and Bayesian phylogenetic models (see supplementary methods). We then ran a unique bioenergetic model for each combination of species identity, body size, and sea surface temperature (n = 30668) to obtain the contribution of each individual to each function in each transect. Finally, we summarized functions at the community level by summing up all individual contributions inside a transect and deviding the sum by the surface area. Each function is thus Epressed as dry mass (of C, N, or P) per day per square meter. We note that N excretion, P excretion, and biomass production include contributions of all fishes, whereas herbivory and piscivory are carried out by a subset of the community, with respect to their trophic guild as defined by @Parravicini2020. To reduce the occurrence of misclassification of herbivores and piscivores, we categorized a species as a herbivore or piscivore if it had both the highest probability to be classified in that trophic group and this probability was more than 0.5, based on the probability scores of trophic guilds presented by Parravicini et al. (2020) [@Parravicini2020]. Further, as a comparison, we quantified herbivory and piscivory rates using two alternative trophic guild classifications based on Expert opinion [@Mouillot2014; @Parravicini2020] (Fig. S5). Both the herbivory and piscivory rates match the Expert opinion trophic guild classifications.
Finally, we estimated multifunction, i.e. one measure that combines all five functions by taking the geometric average of the five functions (normalized to a range between zero and 100). We used the geometric mean because functions are dependent on each other and vary by several orders of magnitude.


### 3. Community structure variables
We quantified a set of variables that characterize fish community structure. These variables describe the size, age, and trophic distribution of the community, as these may all affect functions [@Schiettekatte2020]. Specifically, we calculated the 2.5%, 50%, and 97.5% quantiles of the total length, immaturity, and trophic level of all individuals per transect. The total length is based on visual estimations by divers. The immaturity is quantified using the following formula:
<!-- \begin{equation} -->
	$$\textrm{immaturity}_\textrm{i} = \kappa (\textrm{l}_{\infty} - \textrm{l}_\textrm{i}),$$
<!-- 	\label{imm} -->
<!-- \end{equation} -->
where $\kappa$ is the species-specific growth rate parameter and $l_{\infty}$ is the species-specific asymptotic adult length, and $l_i$ is the total length of individual i. Essentially, this is the derivative of the Von Bertalanffy growth model for a certain length, and the higher this value is, the younger the individual. Finally, trophic level was extracted from Fishbase [@Froese2018].


### 4. Multivariate regression models

We fitted three multivariate Bayesian models with all five functions to (1) predict functions on the locality level to create a maps of functions, (2) investigate the effects of bioimass and SST, and the correlations among functions independent of biomass and SST, and (3) estimate the effects of the community structure on each function. For each model, functions were log-transformed to ensure the normal distribution of residuals and an allometric relationship with biomass, which is hypothesized by metabolic theory [@Brown2004].\par

In the underwater visual transect database, 291 transects (3%) did not contain herbivores and 4467 transects (49%) did not contain piscivores yielding zeros for herbivory and piscivory, respectively. We considered that these absence of herbivores or piscivores are likely an underestimation of their actual abundance at the surveyed reef site, as all reefs typically host a few herbivores and piscivores (i.e. they are likely false-zeros). To avoid removing all transects with missing values for herbivory or piscivory (n = 4,620) from our database when running multivariate analyses, we imputed these zeros as missing values, and they were eventually set as parameters in the multivariate models. \par

First, we performed a multivariate intercept-only regression model with the five log-transformed functions to estimate the functions per locality. The model structure includes intercepts and random effects for localities and sites:

$$\begin{bmatrix}y_{E_{\textrm{N}},i} \\ y_{E_{\textrm{P}},i} \\ y_{B,i} \\ y_{H,i} \\ y_{P,i} \end{bmatrix} \sim MVNormal\left(\begin{bmatrix} \mu_{E_{\textrm{N}},i} \\ \mu_{E_{\textrm{P}},i} \\ \mu_{B,i} \\ \mu_{H,i} \\ \mu_{P,i}\end{bmatrix}, S \right),$$

$$\begin{array}{c} \mu_{E_{\textrm{N}},i}  = (\beta0_{E_{\textrm{N}}}  +  \delta_{E_{\textrm{N}}, loc}  +  \delta_{E_{\textrm{N}}, site}) \\
\mu_{E_{\textrm{P},i}}  = (\beta0_{E_{\textrm{P}}}  +  \delta_{E_{\textrm{P}}, loc}  +  \delta_{E_{\textrm{P}}, site})  \\
\mu_{\textrm{B,i}} = (\beta0_{B} +  \delta_{B, loc} +  \delta_{B, site}) \\
\mu_{\textrm{H,i}} = (\beta0_{H} +  \delta_{H, loc} +  \delta_{H, site}) \\
\mu_{\textrm{P,i}} = (\beta0_{P} +  \delta_{P, loc} +  \delta_{P, site}) , \end{array}$$


$$
S = \begin{bmatrix}
\sigma_{E_{\textrm{N}}} & 0 & 0 & 0 & 0\\
0 & \sigma_{E_{\textrm{P}}} & 0 & 0 & 0 \\
0 & 0 & \sigma_{B,i} & 0 & 0\\
0 & 0 & 0 & \sigma_{H} & 0\\
0 & 0 & 0 & 0 & \sigma_{P}
\end{bmatrix}
R
\begin{bmatrix}
\sigma_{E_{\textrm{N}}} & 0 & 0 & 0 & 0\\
0 & \sigma_{E_{\textrm{P}}} & 0 & 0 & 0 \\
0 & 0 & \sigma_{B,i} & 0 & 0\\
0 & 0 & 0 & \sigma_{H} & 0\\
0 & 0 & 0 & 0 & \sigma_{P}
\end{bmatrix},
$$

where $i$ is the index of the transect, $y_{E_{\textrm{N}},i}$ is the N excretion rate of transect i, $y_{E_{\textrm{P}},i}$ is the P excretion rate, $y_{B,i}$ is the biomass production rate, $y_{H,i}$ is the herbivory rate, $y_{E_{\textrm{N}},i}$ is the piscivory rate, $\sigma$ represents the residual error of each function ($E_{\textrm{N}}$, $E_{\textrm{P}}$, $B$, $H$, and $P$), R is the correlation matrix of the residuals. Locality- and site-level effects are also structured including covariation among functions. There are thus three correlation matrices in total, meaning that the model will estimate the correlation between functions (independent of biomass and SST) on three levels: locality, site, and transect.

\noindent We used non-centered parameterization for site and location effects and all standard deviations had the following prior: $\sigma \sim student(3, 0, 2.5)$. We used a prior (lkj_{corr}) for each of the three correlation matrices ($R \sim lkj\_corr(1)$).


Second, we ran a mixed-effect model to investigate the effects of biomass and SST on all functions and the correlations among functions (independent of biomass and SST).
The standing stock biomass of communities is positively related to all functions because of the additive nature of the quantification and metabolic theory [@Brown2004]. Furthermore, because of the known relationship between temperature and parameters related to growth and respiration (see supplementary methods), functions are expected to be affected by temperature. We thus fitted a multivariate Bayesian mixed-effect model using transect-level log-transformed functions that included random effects for sites and localities:


$$\begin{bmatrix}y_{E_{\textrm{N}},i} \\ y_{E_{\textrm{P}},i} \\ y_{B,i} \\ y_{H,i} \\ y_{P,i} \end{bmatrix} \sim MVNormal\left(\begin{bmatrix} \mu_{E_{\textrm{N}},i} \\ \mu_{E_{\textrm{P}},i} \\ \mu_{B,i} \\ \mu_{H,i} \\ \mu_{P,i}\end{bmatrix}, S \right),$$

$$S = \begin{bmatrix}\sigma_{E_{\textrm{N}}} & 0 & 0 & 0 & 0\\
0 & \sigma_{E_{\textrm{P}}} & 0 & 0 & 0 \\
0 & 0 & \sigma_{B,i} & 0 & 0\\
0 & 0 & 0 & \sigma_{H} & 0\\
0 & 0 & 0 & 0 & \sigma_{P} \end{bmatrix}
R
\begin{bmatrix}\sigma_{E_{\textrm{N}}} & 0 & 0 & 0 & 0\\
0 & \sigma_{E_{\textrm{P}}} & 0 & 0 & 0 \\
0 & 0 & \sigma_{B,i} & 0 & 0\\
0 & 0 & 0 & \sigma_{H} & 0\\
0 & 0 & 0 & 0 & \sigma_{P} \end{bmatrix}$$


$$\begin{array}{c} \mu_{E_{\textrm{N}},i} = (\beta0_{E_{\textrm{N}}} +  \delta_{E_{\textrm{N}}, loc} +  \delta_{E_{\textrm{N}}, site}) +{\beta1_{E_{\textrm{N}}}} {{log(biomass),i}} + {\beta2_{E_{\textrm{N}}}} {{SST,i}} \\
\mu_{E_{\textrm{P}},i} = (\beta0_{E_{\textrm{P}}} +  \delta_{E_{\textrm{P}}, loc} +  \delta_{E_{\textrm{P}}, site}) +{\beta1_{E_{\textrm{P}}}} {{log(biomass),i}} + {\beta2_{E_{\textrm{P}}}} {{SST,i}} \\
\mu_{\textrm{B,i}} = (\beta0_{B} +  \delta_{B, loc} +  \delta_{B, site}) +{\beta1_{B}} {{log(biomass),i}} + {\beta2_{B}} {{SST,i}} \\
\mu_{\textrm{H,i}} = (\beta0_{H} +  \delta_{H, loc} +  \delta_{H, site}) +{\beta1_{H}} {{log(biomass),i}} + {\beta2_{H}} {{SST,i}} \\
\mu_{\textrm{P,i}} = (\beta0_{P} +  \delta_{P, loc} +  \delta_{P, site}) +{\beta1_{P}} {{log(biomass),i}} + {\beta2_{P}} {{SST,i}} \end{array}
$$

where $\beta1_{E_{\textrm{N}}}, \beta1_{E_{\textrm{P}}}, \beta1_{B}, \beta1_{H}, \beta1_{P}$ are the fixed effects of the log-transformed biomass, and $\beta2_{E_{\textrm{N}}}, \beta2_{E_{\textrm{P}}}, \beta2_{B}, \beta2_{H}, \beta2_{P}$ are the fixed effects of SST. Locality- and site-level effects are thus structured including covariation among functions, independent of biomassand SST. Similarly, the residual variation of functions incorporates the correlations between functions, without the effect of biomass and SST.
We used similar priors as described above, and we used weakly-informative normal priors for the model slopes ($\beta1 \sim normal(1,1)$, $\beta2 \sim normal(0,1)$).

\noindent Finally, to investigate the effect of community structure while still accounting for the effects of standing biomass and SST, we fitted a mixed effect multivariate model similar to the model specified above, but adding all community structure variables:

$$\begin{array}{c} \mu_{\textrm{function,i}}  = \beta0_{function} + \beta1_{function} {log(biomass),i} + \beta2_{function} {SST,i}  + \beta3_{function} {richness,i}  + \beta4_{function} {size_m,i}  + \beta5_{function} {size_{2.5\%},i} +  \beta6_{function} {size_{97.5\%},i} + \\
\beta7_{function} {troph_m,i}  + \beta8_{function} {troph_{2.5\%},i} +  \beta9_{function} {troph_{97.5\%},i} + \beta10_{function} {imm_m,i}  + \beta11_{function} {imm_{2.5\%},i} +  \beta12_{function} {imm_{97.5\%},i} \end{array}$$

where $richness$ is the species richness, $size$ is the total length, $troph$ is the trophic level, $imm$ is the immaturity, and $m$, $2.5\%$, and $97.5\%$ represent the 50\%, 2.5\%, and 97.5\% quantiles across the fish community, respectively.
For these models, we used weakly informative priors for the fixed effect parameters ($\beta3-\beta12 \sim normal(0,1)$) and the same priors as described above for other parameters. par

All Bayesian models were fitted using the R package *brms* [@Burkner2017], which uses Stan, a C++ package to perform full Bayesian inference [@Carpenter2017]. The posterior distributions of model parameters were estimated using Hamiltonian Monte Carlo (HMC) methods by using four chains of 2,000 samples, including 1,000 samples as a warm‐up. Thus, a total of 4,000 draws were used to estimate posterior distributions. The convergence and fit of the models were verified by examining the Rhat, parameter trace plots, and posterior prediction plots (Fig S2).


### 5. Species dominance and contributions to functions
We quantified the relative contribution of each species to each function for all sites as follows:
<!-- \begin{equation} -->
$$	\textrm{contribution}_{f,i,j} = \frac{F_{f,i,j}}{\sum F_{f,j}},$$
<!-- 	\label{con} -->
<!-- \end{equation} -->
where i is a certain species, j is a site, F is the value of function f.

Then, we quantified the degree of species dominance per function for each site. We first ranked species according to their contribution to function, then we quantified the cumulative contributions of species to functions. Finally, we used the area under the species accumulation curve as a measure for the degree of dominance. Specifically, the degree of dominance (DD) for a function performed by R species was calculated as follows:

<!-- \begin{equation} -->
$$	\textrm{DD} = \frac{A - A_{min}}{A_{max} - A_{min}},$$
<!-- 	\label{dd} -->
<!-- \end{equation} -->
where $A$ is the area under the curve, $A_{min}$ is the theoretical area under the curve where each species has an equal contribution to a certain function, and $A_max$ is the theoretical area under the curve where one species performs the entire function. They are quantified as:
<!-- \begin{equation} -->
$$	\textrm{A}_{min} = \frac{R^2 - 1}{2 R},$$
<!-- 	\label{Amin} -->
<!-- \end{equation} -->

<!-- \begin{equation} -->
$$	\textrm{A}_{max} = R - 1,$$
<!-- 	\label{Amax} -->
<!-- \end{equation} -->

<!-- \begin{equation} -->
$$	\textrm{A} = \sum_{i = 2}^R \frac{C_i + C_{i-1}}{2},$$
<!-- 	\label{A} -->
<!-- \end{equation} -->

where $C_i$ is the contribution of a certain species and R R equals the species richness in the case of N excretion, P excretion, and production. For herbivory and piscivory, R represents the number of herbivores and piscivores, respectively. The degree of dominance thus ranges between 0 and 1, where 0 means that each species contributes equally and 1 means that a single species performs the entire function.

Finally, we quantified the frequency of dominance per species (i.e. the number of sites in which a species is dominant for a given function divided by the total number of sites in which that species is observed). A species is considered dominant for a certain function in a given site if their contribution is higher than 1/R (i.e. they contribute more than the situation in which each species contributes equally to a certain function).






<br>

**References**
<div id="refs"></div>


**Acknowledgements:**
We thank the staff at CRIOBE, Moorea for field support. We would also like to thank Jérémy Carlot, Beverly French, Titouan Roncin, Yann Lacube, Camille Gache, Gabrielle Martineau, Kailey Bissell, Benoit Espiau, Calvin Quigley, Kaitlyn Landfield and Tommy Norin for their help in the field, Guillemette de Sinéty and Jérémy Wicquart for their contribution to otolith analysis, and Sophie Schiettekatte for proof-reading the manuscript. .
This research was funded by the BNP Paribas Foundation (Reef Services Project) and the French National Agency for Scientific Research (ANR; REEFLUX Project; ANR‐17‐CE32‐0006). This research is product of the SCORE-REEF group funded by the Centre de Synthèse et d’Analyse sur la Biodiversité (CESAB) of the Foundation pour la Recherche sur la Biodiversité (FRB) and the Agence Nationale de la Biodiversité (AFB). VP was supported by the Institut Universitaire de France (IUF) and JMC was supported by a Make Our Planet Great Again Postdoctoral Grant (mopga‐pdf‐0000000144).
**Author contributions:**
NMDS and VP conceived the idea and NMDS, VP, SJB, and JMC designed methodology; NMDS, JMC, SJB, AM, FM, VP, KSM, JEA and DEB collected the data; All authors shared existing data. NMDS analyzed the data and led the writing of the manuscript. All authors contributed significantly to the drafts and approved the final version for publication.
**Competing interests:** None declared.
**Data and materials availability:**
All data and code to reproduce the figures are available on GitHub (https://github.com/nschiett/global_proc) and figshare (https://figshare.com/s/f789aec2c20492c4f0f9). All data on individual empirical measurements are available from the corresponding author upon request.


**Figure legends**

Fig. 1: Maps of the five key ecosystem functions, multifunctionality, and the relationships between the functions and biomass. Left: Dots indicate localities of field surveys, with dot sizes representing the ranked values of the locality-level predictions of functions, and color scales showing categorical assignments (black = < 25\%, grey = 25-75\%, color = >75\%). Black outlines highlight the five localities with the highest values of each function. Multifunctionality represents the weighted average of the five standardized functions. Right: The predicted values for functions and multifunctionality with increasing biomass. The lines represent the average modeled relationship and the shaded areas show the 95\% credible intervals of the predictions.

Fig. 2: Correlations of the five functions, accounting for biomass and sea surface temperature. a: Modeled correlation coefficients of residual errors. Dots represent the average and lines represent the 95%CI. b-k: Scatter plots of the mean residual errors of the functions.


Fig. 3.  Effects of ecological community variables on the five functions. Dots indicate fixed effect values from Bayesian linear regressions that examine the effects of species richness, trophic level, size, and immaturity of fishes. To represent both the median and spread of trophic level, size, and immaturity across individuals within a community, we included lower and upper 95% quantile values of these three traits as community variables. All data were log-transformed and standardized to compare across functions and variables (see Table S2 for parameter values on non-standardized data). Dots represent the average effect size estimate, and horizontal lines indicate the 95% credible interval. Immaturity is defined as the derivative of the von Bertalanffy growth model for a given size; thus, the higher this value, the younger the individual.

Fig. 4: Local dominance in species contributions to five ecosystem functions on coral reefs. a: The degree of dominance for each function at the site level. The degree of dominance of a community ranges between zero (all species contribute equally to the function) and one (a single species is the sole contributor to a given function). Colored dots represent the raw values, and the black dots and lines display the mean and 95\% credible intervals of degree of dominance among all sites. In some cases, the credible interval was too small to be visible. The vertical dashed line shows the average degree of dominance of 1,000 randomly simulated communities. b: Bar plot of the proportion of species that are dominant in at least one site relative to the total number of species, or, for herbivory and piscivory, the total number of herbivores and piscivores, respectively. c: Species-specific frequencies of dominance in each function across all sites, ranging from zero (species are never dominant) to one (dominant wherever present). A species is categorized as dominant in a community if its contribution to a function is higher than a scenario in which all species are equal (i.e. one divided by the number of species that contribute to the function).


Fig. 5. Vulnerability of the five functions to fishing and climate change-induced coral loss. Conceptual scheme of the potential ways in which fishing and climate change can affect functions through their known effects on biomass and community structure.
