---
output:
  word_document:
    fig_caption: yes
    reference_docx: ../text/word_template.docx
bibliography: ../text/global_proc.bib
csl: nature.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Methods

## 1. Underwater visual census database
\noindent We used a published global database of reef fish abundances and sizes collected along belt transects [@Barneche2019]. This database encompasses 9,118 transects across 585 sites (within 98 localities) in the Central Indo-Pacific, Central Pacific, Eastern Pacific, Western Indian, Eastern Atlantic, and Western Atlantic Oceans. Sites are defined as small islands or stretches of continuous reefs in larger coastlines and localities encompass sites that belong to the same biogeographic sub-provinces [see @Barneche2019]. The database only includes transects on the outer reef slope and with a hard reef bottom. Transects were carried out at a constant depth, parallel to the reef crest. We discarded the species inside families for which we did not have body stoichiometry data, individuals that were smaller than 7cm (to minimize the bias related to the identification of small individuals), and rare species for which less than 20 individuals were recorded across all transects. The dataset then included 1,110 species belonging to 25 families (Acanthuridae, Balistidae, Bothidae, Chaetodontidae, Cirrhitidae, Fistulariidae, Haemulidae, Holocentridae, Kyphosidae, Labridae, Lethrinidae, Lutjanidae, Monacanthidae, Mugilidae, Mullidae, Ostraciidae, Pempheridae, Pomacanthidae, Pomacentridae, Sciaenidae, Scorpaenidae, Serranidae, Siganidae, Tetraodontidae, Zanclidae).
Sea surface temperature (SST) for each site was obtained from daily time‐series data from the National Oceanicand Atmospheric Administration (NOAA) covering a 5‐year period (°C; 0.25° resolution) (@Reynolds2007; available from https://www.esrl.noaa.gov/psd/data/gridded/data.noaa.oiSST.v2.highres.html). Further, for each transect, we calculated species richness and estimated total standing stock biomass of fishes by using Bayesian length-weight relationships available from Fishbase [@Froese2014]. All data processing and analyses were performed in the software program R (version 4.0.2; R core team 2020).

## 2. Quantification of functions
\noindent For each transect, we estimated five key process-based functions mediated by fishes: nitrogen excretion rate (gN m^-2^ day^-1^), phosphorus excretion rate (gP m^-2^ day^-1^), production of biomass through growth (gC m^-2^ day^-1^), herbivory, (i.e. ingestion rate of macrophytes (gC m^-2^ day^-1^)), and piscivory (i.e. ingestion rate of fishes ( m^-2^ day^-1^)) [@Brandl2019front]. These five functions were estimated for each transect using individual-based bioenergetic models predicting fluxes of carbon (C), nitrogen (N), and phosphorus (P) (e.g. daily C intake rates, N and P excretion rates, and growth rates) [@Schiettekatte2020].
This bioenergetic model framework integrates elements of metabolic theory, stoichiometry, and flexible elemental limitation [@Schiettekatte2020]. We quantified the input parameters, including elements of metabolism, growth, and diet and body stoichiometry, for all 1110 species through the integration of empirical data, data synthesis, and Bayesian phylogenetic models (see supplementary methods). We then ran a unique bioenergetic model for each combination of species identity, body size, and sea surface temperature (n = 30668) to obtain the contribution of each individual to each function in each transect. Finally, we summarized functions at the community level by summing up all individual contributions inside a transect and deviding the sum by the surface area. Each function is thus E_{textrm{P}}ressed as dry mass (of C, N, or P) per day per square meter. We note that N excretion, P excretion, and biomass production include contributions of all fishes, whereas herbivory and piscivory are carried out by a subset of the community, with respect to their trophic guild as defined by @Parravicini2020. To reduce the occurrence of misclassification of herbivores and piscivores, we categorized a species as a herbivore or piscivore if it had both the highest probability to be classified in that trophic group and this probability was more than 0.5, based on the probability scores of trophic guilds presented by Parravicini et al. (2020) [@Parravicini2020]. Further, as a comparison, we quantified herbivory and piscivory rates using two alternative trophic guild classifications based on E_{textrm{P}}ert opinion [@Mouillot2014; @Parravicini2020] (Fig. S5). Both the herbivory and piscivory rates match the E_{textrm{P}}ert opinion trophic guild classifications.
Finally, we estimated multifunction, i.e. one measure that combines all five functions by taking the geometric average of the five functions (normalized to a range between zero and 100). We used the geometric mean because functions are dependent on each other and vary by several orders of magnitude.


## 3. Community structure variables
We quantified a set of variables that characterize fish community structure. These variables describe the size, age, and trophic distribution of the community, as these may all affect functions [@Schiettekatte2020]. Specifically, we calculated the 2.5%, 50%, and 97.5% quantiles of the total length, immaturity, and trophic level of all individuals per transect. The total length is based on visual estimations by divers. The immaturity is quantified using the following formula:
<!-- \begin{equation} -->
	$$\textrm{immaturity}_\textrm{i} = \kappa (\textrm{l}_{\infty} - \textrm{l}_\textrm{i}),$$
<!-- 	\label{imm} -->
<!-- \end{equation} -->
where $\kappa$ is the species-specific growth rate parameter and $l_{\infty}$ is the species-specific asymptotic adult length, and $l_i$ is the total length of individual i. Essentially, this is the derivative of the Von Bertalanffy growth model for a certain length, and the higher this value is, the younger the individual. Finally, trophic level was extracted from Fishbase [@Froese2018].


## 4. Multivariate regression models

We fitted three multivariate Bayesian models with all five functions to (1) predict functions on the locality level to create a maps of functions, (2) investigate the effects of bioimass and SST, and the correlations among functions independent of biomass and SST, and (3) estimate the effects of the community structure on each function. For each model, functions were log-transformed to ensure the normal distribution of residuals and an allometric relationship with biomass, which is hypothesized by metabolic theory [@Brown2004].\par

In the underwater visual transect database, 291 transects (3%) did not contain herbivores and 4467 transects (49%) did not contain piscivores yielding zeros for herbivory and piscivory, respectively. We considered that these absence of herbivores or piscivores are likely an underestimation of their actual abundance at the surveyed reef site, as all reefs typically host a few herbivores and piscivores (i.e. they are likely false-zeros). To avoid removing all transects with missing values for herbivory or piscivory (n = 4,620) from our database when running multivariate analyses, we imputed these zeros as missing values, and they were eventually set as parameters in the multivariate models. \par

First, we performed a multivariate intercept-only regression model with the five log-transformed functions to estimate the functions per locality. The model structure includes intercepts and random effects for localities and sites:

$$\begin{bmatrix}y_{E_{textrm{N}},i} \\ y_{E_{textrm{P}},i} \\ y_{B,i} \\ y_{H,i} \\ y_{P,i} \end{bmatrix} \sim MVNormal\left(\begin{bmatrix} \mu_{E_{textrm{N}},i} \\ \mu_{E_{textrm{P}},i} \\ \mu_{B,i} \\ \mu_{H,i} \\ \mu_{P,i}\end{bmatrix}, S \right),$$

$$
\begin{array}{c} \mu_{\textrm{E_{textrm{N}},i}}  = (\beta0_{E_{textrm{N}}}  +  \delta_{E_{textrm{N}}, loc}  +  \delta_{E_{textrm{N}}, site}) \\
\mu_{\textrm{E_{textrm{P}},i}}  = (\beta0_{E_{textrm{P}}}  +  \delta_{E_{textrm{P}}, loc}  +  \delta_{E_{textrm{P}}, site})  \\
\mu_{\textrm{B,i}} = (\beta0_{B} +  \delta_{B, loc} +  \delta_{B, site}) \\
\mu_{\textrm{H,i}} = (\beta0_{H} +  \delta_{H, loc} +  \delta_{H, site}) \\
\mu_{\textrm{P,i}} = (\beta0_{P} +  \delta_{P, loc} +  \delta_{P, site}) , \end{array}
$$

$$
S = \begin{bmatrix}
\sigma_{E_{textrm{N}}} & 0 & 0 & 0 & 0\\
0 & \sigma_{E_{textrm{P}}} & 0 & 0 & 0 \\
0 & 0 & \sigma_{B,i} & 0 & 0\\
0 & 0 & 0 & \sigma_{H} & 0\\
0 & 0 & 0 & 0 & \sigma_{P}
\end{bmatrix}
R
\begin{bmatrix}
\sigma_{E_{textrm{N}}} & 0 & 0 & 0 & 0\\
0 & \sigma_{E_{textrm{P}}} & 0 & 0 & 0 \\
0 & 0 & \sigma_{B,i} & 0 & 0\\
0 & 0 & 0 & \sigma_{H} & 0\\
0 & 0 & 0 & 0 & \sigma_{P}
\end{bmatrix},
$$

where $i$ is the index of the transect, $y_{E_{textrm{N}},i}$ is the N excretion rate of transect i, $y_{E_{textrm{P}},i}$ is the P excretion rate, $y_{B,i}$ is the biomass production rate, $y_{H,i}$ is the herbivory rate, $y_{E_{textrm{N}},i}$ is the piscivory rate, $\sigma$ represents the residual error of each function ($E_{textrm{N}}$, $E_{textrm{P}}$, $B$, $H$, and $P$), R is the correlation matrix of the residuals. Locality- and site-level effects are also structured including covariation among functions. There are thus three correlation matrices in total, meaning that the model will estimate the correlation between functions (independent of biomass and SST) on three levels: locality, site, and transect.

\noindent We used non-centered parameterization for site and location effects and all standard deviations had the following prior: $\sigma \sim student(3, 0, 2.5)$. We used a prior (lkj_{corr}) for each of the three correlation matrices ($R \sim lkj\_corr(1)$).


Second, we ran a mixed-effect model to investigate the effects of biomass and SST on all functions and the correlations among functions (independent of biomass and SST).
The standing stock biomass of communities is positively related to all functions because of the additive nature of the quantification and metabolic theory [@Brown2004]. Furthermore, because of the known relationship between temperature and parameters related to growth and respiration (see supplementary methods), functions are expected to be affected by temperature. We thus fitted a multivariate Bayesian mixed-effect model using transect-level log-transformed functions that included random effects for sites and localities:


$$\begin{bmatrix}y_{E_{textrm{N}},i} \\ y_{E_{textrm{P}},i} \\ y_{B,i} \\ y_{H,i} \\ y_{P,i} \end{bmatrix} \sim MVNormal\left(\begin{bmatrix} \mu_{E_{textrm{N}},i} \\ \mu_{E_{textrm{P}},i} \\ \mu_{B,i} \\ \mu_{H,i} \\ \mu_{P,i}\end{bmatrix}, S \right),$$

$$S = \begin{bmatrix}\sigma_{E_{textrm{N}}} & 0 & 0 & 0 & 0\\
0 & \sigma_{E_{textrm{P}}} & 0 & 0 & 0 \\
0 & 0 & \sigma_{B,i} & 0 & 0\\
0 & 0 & 0 & \sigma_{H} & 0\\
0 & 0 & 0 & 0 & \sigma_{P} \end{bmatrix}
R
\begin{bmatrix}\sigma_{E_{textrm{N}}} & 0 & 0 & 0 & 0\\
0 & \sigma_{E_{textrm{P}}} & 0 & 0 & 0 \\
0 & 0 & \sigma_{B,i} & 0 & 0\\
0 & 0 & 0 & \sigma_{H} & 0\\
0 & 0 & 0 & 0 & \sigma_{P} \end{bmatrix}$$


$$\begin{array}{c} \mu_{\textrm{E_{textrm{N}},i}} = (\beta0_{E_{textrm{N}}} +  \delta_{E_{textrm{N}}, loc} +  \delta_{E_{textrm{N}}, site}) +{\beta1_{E_{textrm{N}}}} {{log(biomass),i}} + {\beta2_{E_{textrm{N}}}} {{SST,i}} \\
\mu_{\textrm{E_{textrm{P}},i}} = (\beta0_{E_{textrm{P}}} +  \delta_{E_{textrm{P}}, loc} +  \delta_{E_{textrm{P}}, site}) +{\beta1_{E_{textrm{P}}}} {{log(biomass),i}} + {\beta2_{E_{textrm{P}}}} {{SST,i}} \\
\mu_{\textrm{B,i}} = (\beta0_{B} +  \delta_{B, loc} +  \delta_{B, site}) +{\beta1_{B}} {{log(biomass),i}} + {\beta2_{B}} {{SST,i}} \\
\mu_{\textrm{H,i}} = (\beta0_{H} +  \delta_{H, loc} +  \delta_{H, site}) +{\beta1_{H}} {{log(biomass),i}} + {\beta2_{H}} {{SST,i}} \\
\mu_{\textrm{P,i}} = (\beta0_{P} +  \delta_{P, loc} +  \delta_{P, site}) +{\beta1_{P}} {{log(biomass),i}} + {\beta2_{P}} {{SST,i}} \end{array}
$$

where $\beta1_{E_{textrm{N}}}, \beta1_{E_{textrm{P}}}, \beta1_{B}, \beta1_{H}, \beta1_{P}$ are the fixed effects of the log-transformed biomass, and $\beta2_{E_{textrm{N}}}, \beta2_{E_{textrm{P}}}, \beta2_{B}, \beta2_{H}, \beta2_{P}$ are the fixed effects of SST. Locality- and site-level effects are thus structured including covariation among functions, independent of biomassand SST. Similarly, the residual variation of functions incorporates the correlations between functions, without the effect of biomass and SST.
We used similar priors as described above, and we used weakly-informative normal priors for the model slopes ($\beta1 \sim normal(1,1)$, $\beta2 \sim normal(0,1)$).

\noindent Finally, to investigate the effect of community structure while still accounting for the effects of standing biomass and SST, we fitted a mixed effect multivariate model similar to the model specified above, but adding all community structure variables:

$$\begin{array}{c} \mu_{\textrm{function,i}}  = \beta0_{function} + \beta1_{function} {log(biomass),i} + \beta2_{function} {SST,i}  + \beta3_{function} {richness,i}  + \beta4_{function} {size_m,i}  + \beta5_{function} {size_{2.5\%},i} +  \beta6_{function} {size_{97.5\%},i} + \\
\beta7_{function} {troph_m,i}  + \beta8_{function} {troph_{2.5\%},i} +  \beta9_{function} {troph_{97.5\%},i} + \beta10_{function} {imm_m,i}  + \beta11_{function} {imm_{2.5\%},i} +  \beta12_{function} {imm_{97.5\%},i} \end{array}$$

where $richness$ is the species richness, $size$ is the total length, $troph$ is the trophic level, $imm$ is the immaturity, and $m$, $2.5\%$, and $97.5\%$ represent the 50\%, 2.5\%, and 97.5\% quantiles across the fish community, respectively.
For these models, we used weakly informative priors for the fixed effect parameters ($\beta3-\beta12 \sim normal(0,1)$) and the same priors as described above for other parameters. par

All Bayesian models were fitted using the R package *brms* [@Burkner2017], which uses Stan, a C++ package to perform full Bayesian inference [@Carpenter2017]. The posterior distributions of model parameters were estimated using Hamiltonian Monte Carlo (HMC) methods by using four chains of 2,000 samples, including 1,000 samples as a warm‐up. Thus, a total of 4,000 draws were used to estimate posterior distributions. The convergence and fit of the models were verified by examining the Rhat, parameter trace plots, and posterior prediction plots (Fig S2).


## 5. Species dominance and contributions to functions
We quantified the relative contribution of each species to each function for all sites as follows:
<!-- \begin{equation} -->
$$	\textrm{contribution}_{f,i,j} = \frac{F_{f,i,j}}{\sum F_{f,j}},$$
<!-- 	\label{con} -->
<!-- \end{equation} -->
where i is a certain species, j is a site, F is the value of function f.

Then, we quantified the degree of species dominance per function for each site. We first ranked species according to their contribution to function, then we quantified the cumulative contributions of species to functions. Finally, we used the area under the species accumulation curve as a measure for the degree of dominance. Specifically, the degree of dominance (DD) for a function performed by R species was calculated as follows:

<!-- \begin{equation} -->
$$	\textrm{DD} = \frac{A - A_{min}}{A_{max} - A_{min}},$$
<!-- 	\label{dd} -->
<!-- \end{equation} -->
where $A$ is the area under the curve, $A_{min}$ is the theoretical area under the curve where each species has an equal contribution to a certain function, and $A_max$ is the theoretical area under the curve where one species performs the entire function. They are quantified as:
<!-- \begin{equation} -->
$$	\textrm{A}_{min} = \frac{R^2 - 1}{2 R},$$
<!-- 	\label{Amin} -->
<!-- \end{equation} -->

<!-- \begin{equation} -->
$$	\textrm{A}_{max} = R - 1,$$
<!-- 	\label{Amax} -->
<!-- \end{equation} -->

<!-- \begin{equation} -->
$$	\textrm{A} = \sum_{i = 2}^R \frac{C_i + C_{i-1}}{2},$$
<!-- 	\label{A} -->
<!-- \end{equation} -->

where $C_i$ is the contribution of a certain species and R R equals the species richness in the case of N excretion, P excretion, and production. For herbivory and piscivory, R represents the number of herbivores and piscivores, respectively. The degree of dominance thus ranges between 0 and 1, where 0 means that each species contributes equally and 1 means that a single species performs the entire function.

Finally, we quantified the frequency of dominance per species (i.e. the number of sites in which a species is dominant for a given function divided by the total number of sites in which that species is observed). A species is considered dominant for a certain function in a given site if their contribution is higher than 1/R (i.e. they contribute more than the situation in which each species contributes equally to a certain function).




## References
